# Generated by Django 5.2.7 on 2025-11-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
